### ISSUE TITLE
Problem with long labels

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1164]
![labelproblem](https://cloud.githubusercontent.com/assets/8279974/15603555/7474a0a4-240c-11e6-9739-fd24398a2bd4.png)
Problem appears in 3.3 and 3.4. Fast fix for this:
```css
.inline input[type='checkbox']+label {
	display: inline;
}
```
