### ISSUE TITLE
imageless nav arrows

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#681]
Would like to replace the arrow images with css.

here is a test for sidemenus

``` css
/* sidebar current arrow */
#sidebar .snav li a.current,#sidebar .snav li a.current:hover {
    position: relative;

    /* overrides */
    background: none !important;
    background-color: #CF3805 !important;
    height:14px;
    margin-left:13px;
    padding-left:15px;
}
#sidebar .snav li a.current:after {
    right: 100%;
    border: solid transparent;
    content: " ";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
}

#sidebar .snav li a.current:after {
    border-color: rgba(207, 56, 5, 0);
    border-right-color: #CF3805;
    border-width: 1em;
    top: 50%;
    margin-top: -1em;
}
```
